---
# The logger integration lets you define the level of logging activities
# in Home Assistant.
#
# I use this to reduce error messages for specific things,
# so I can focus on log messages that matter to me.
#
logger:
  default: warning

  filters:
    homeassistant.helpers.template:
      # Zigbee2MQTT template warnings, supress for now
      - "Template variable warning: 'dict object' has no attribute 'action' when rendering '{{ value_json.action }}'"
      - "Template variable warning: 'dict object' has no attribute 'linkquality' when rendering '{{ value_json.linkquality }}'"
      - "Template variable warning: 'dict object' has no attribute 'sensitivity' when rendering '{{ value_json.sensitivity }}'"
