---
# Time
#
# The time component allows you to set up real time clock time sources
# for ESPHome.
#
# https://esphome.io/components/time.html
#
substitutions:
  time_timezone: "Europe/Amsterdam"

time:
  - <<: !include ../time/homeassistant.yaml
    timezone: "${time_timezone}"
    on_time_sync:
      - component.update: sensor_uptime_timestamp

  - <<: !include ../time/sntp.yaml
    timezone: "${time_timezone}"

sensor:
  - <<: !include ../sensors/uptime.yaml
  - platform: template
    id: sensor_uptime_timestamp
    name: "${name} Uptime"
    icon: "mdi:clock"
    device_class: "timestamp"
    accuracy_decimals: 0
    update_interval: never
    lambda: |-
      static float timestamp = (
        id(time_homeassistant).utcnow().timestamp - id(sensor_uptime).state
      );
      return timestamp;
