---
alias: "Yeah boy?"
use_blueprint:
  path: homeassistant/confirmable_notification.yaml
  input:
    notify_device: f7b8accda76f4fe7a8306dcb1a4e5865
    title: "Yeah boy?"
    message: "Time for a meme?"
    confirm_text: "Yeah boy!"
    confirm_action:
      - service: media_player.play_media
        target:
          entity_id: media_player.office_desk
        data:
          media_content_id: >-
            {
              "app_name": "youtube",
              "media_id": "YFE8UXTsMoA"
            }
          media_content_type: cast
