---
alias: Kitchen Remote
description: >-
  The kitchen remote, using the Philips Hue Remote (RWL021).

  It allows for manually change the lights in the kitchen.

id: 52d4f6b3-744c-4d87-81df-6acc80e9121c

use_blueprint:
  path: zigbee2mqtt_hue_remote_simple.yaml
  input:
    remote: sensor.kitchen_remote_action
    light:
      entity_id: light.kitchen_ceiling
    force_brightness: true
    brightness: 50
