---
alias: Attic Ventilation
description: >-
  Controls the speed of the central ventilation system

  My central ventilation system is controlled by Sonoff Dual R2, running
  ESPHome. The ESPHome code can be found in the `esphome` folder, file:
  `attic_ventilation.yaml`.

  It handles two cases:
    - The humidity of the bathroom.
    - Turn on ventilation when someone visits the restroom long enough to
      indicate it is a number 2 ;)

id: "c2153826-fa86-4448-91a5-53791f86a5f5"
mode: single
max_exceeded: silent

trigger:
  - platform: homeassistant
    event: start

  - platform: event
    event_type: automation_reloaded

  - platform: state
    entity_id:
      - sensor.bathroom_humidity

  - platform: state
    entity_id: light.restroom
    to: "off"
    for:
      minutes: 10

  - platform: state
    entity_id: light.restroom
    to: "on"
    for:
      minutes: 3

condition:
  - condition: state
    entity_id: input_boolean.attic_automatic_ventilation
    state: "on"

action:
  choose:
    # High speed
    - conditions:
        - condition: not
          conditions:
            - condition: state
              entity_id: alarm_control_panel.house_alarm
              state: armed_home
        - condition: or
          conditions:
            - condition: state
              entity_id: binary_sensor.attic_boiler_hot_tap_water
              state: "on"
            - condition: numeric_state
              entity_id: sensor.bathroom_humidity
              above: input_number.setting_bathroom_humidity_high
            - condition: state
              entity_id: light.restroom
              state: "on"
              for:
                minutes: 3
      sequence:
        - service: fan.turn_on
          target:
            entity_id: fan.attic_ventilation
          data:
            percentage: 100

    # Low speed
    - conditions:
        - condition: numeric_state
          entity_id: sensor.bathroom_humidity
          above: input_number.setting_bathroom_humidity_low
          below: input_number.setting_bathroom_humidity_high
      sequence:
        - service: fan.turn_on
          target:
            entity_id: fan.attic_ventilation
          data:
            percentage: 50

  default:
    # Default to off
    - service: fan.turn_off
      target:
        entity_id: fan.attic_ventilation
