---
alias: Landing Automatic Lighting On
description: >-
  Reset / turn on landing automatic lighting when alarm is armed,
  or early in the morning

  It gets turned off when a manual override is detected, but will reset itself
  every night, or when the alarm gets armed.

id: 8950e60b-ae02-40dc-acad-37ef7d9996f6

use_blueprint:
  path: automatic_control_on.yaml
  input:
    toggle: input_boolean.landing_automatic_lighting
