---
alias: Garden Automatic Lighting Off
description: >-
  Turn off automatic garden lighting when a user made manual changes

  It turns off a input_boolean when the lights are changed by a user.
  This allows me to know if the lights are manually overriden, so I can stop
  automating those lights. The input_boolean resets based on other factors,
  for example, the alarm got armed or after a certain time.

id: 13ebd207-c227-4056-bdb7-23fc1c1f0f37

use_blueprint:
  path: automatic_control_off.yaml
  input:
    toggle: input_boolean.garden_automatic_lighting
    entities:
      - light.garden_border_back_left
      - light.garden_border_back_right
      - light.garden_border_front
      - light.garden_veranda_wall
      - light.garden_veranda_wall_left
      - light.garden_veranda_wall_right
      - light.garden_veranda_wall_shed
      - light.garden_wall
      - light.garden_wall_left
      - light.garden_wall_right
