---
alias: Hall Automatic Lighting On
description: >-
  Reset / turn on hall automatic lighting when alarm is armed,
  or early in the morning

  It gets turned off when a manual override is detected, but will reset itself
  every night, or when the alarm gets armed.

id: afc63b2a-7d6a-4d65-8396-c3c9b5511361

use_blueprint:
  path: automatic_control_on.yaml
  input:
    toggle: input_boolean.hall_automatic_lighting
