---
alias: Hall Automatic Lighting Off
description: >-
  Turn off automatic hall lighting when a user made manual changes

  It turns off a input_boolean when the lights are changed by a user.
  This allows me to know if the lights are manually overriden, so I can stop
  automating those lights. The input_boolean resets based on other factors,
  for example, the alarm got armed or after a certain time.

id: 2a92864d-2ff3-4888-9569-d0267303e9ff

use_blueprint:
  path: automatic_control_off.yaml
  input:
    toggle: input_boolean.hall_automatic_lighting
    entities:
      - light.hall_ceiling
