---
alias: Living Room Automatic Lighting On
description: >-
  Reset / turn on living room automatic lighting when alarm is armed,
  or early in the morning

  It gets turned off when a manual override is detected, but will reset itself
  every night, or when the alarm gets armed.

id: 20bfea99-da13-44b5-b78a-9820a409cb4f

use_blueprint:
  path: automatic_control_on.yaml
  input:
    toggle: input_boolean.living_room_automatic_lighting
