---
alias: Bathroom Lights Off
description: >-
  Turn lights off in our bathroom when the alarm is armed.

id: c50e3d67-c377-40e6-aefa-9ea679efa603

use_blueprint:
  path: alarm_armed_lights_off.yaml
  input:
    lights:
      area_id: bathroom
