---
alias: Garden Lights off
description: >-
  Turns off the lights in the garden based on the state of the alarm,
  or based on luminosity.

id: c9c64055-42cd-41c7-99f6-dbce7e4f915d
mode: single

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - alarm_control_panel.house_alarm
      - input_boolean.garden_automatic_lighting
      - sensor.garden_luminosity

condition:
  - condition: or
    conditions:
      - condition: state
        entity_id: alarm_control_panel.house_alarm
        state:
          - armed_away
          - armed_home
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.garden_automatic_lighting
            state: "on"
          - condition: numeric_state
            entity_id: sensor.garden_luminosity
            above: 400.0

action:
  - service: light.turn_off
    target:
      area_id: garden
    data:
      transition: 5
