---
alias: Garden Lights On
description: >-
  Turn garden lights on.

  It turns on the garden lights, when it gets dark. It also turns them
  back to automatic lighting, when the door is closed for some time again.

  Every 5 minutes, this automation is triggered as well. If all conditions match
  it will adjust the lights.

id: 5dc7b352-589a-4ac1-b59a-009270699576
mode: single

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - alarm_control_panel.house_alarm
      - binary_sensor.garden_door
      - input_boolean.garden_automatic_lighting
      - sensor.garden_luminosity
  - platform: state
    entity_id:
      - binary_sensor.garden_door
    to: "off"
    for:
      minutes: 5
  - platform: time_pattern
    minutes: 5

condition:
  - condition: state
    entity_id: input_boolean.garden_automatic_lighting
    state: "on"
  - condition: state
    entity_id: alarm_control_panel.house_alarm
    state: disarmed
  - condition: or
    conditions:
      - condition: state
        entity_id: binary_sensor.garden_door
        state: "unavailable"
      - condition: state
        entity_id: binary_sensor.garden_door
        state: "off"
        for:
          minutes: 5
  - condition: numeric_state
    entity_id: sensor.garden_luminosity
    below: 300.0

action:
  - service: script.sunlight
    data:
      entities:
        - light.garden_border_back_left
        - light.garden_border_back_right
        - light.garden_border_front
        - light.garden_veranda_wall_left
        - light.garden_veranda_wall_right
        - light.garden_veranda_wall_shed
        - light.garden_wall_left
        - light.garden_wall_right
      turn_on: true
