---
# Unused; esp13
#
# Currently not in use, but here to be able to set it up
# again easily when needed.
#
# Its a Gosund SP1.
# https://frenck.link/gosund-sp1
#
substitutions:
  label: esp13
  slug: unused_esp13
  name: Unused esp13
  description: Unused Gosund SP1.
  api_password: !secret esphome_unused_esp13_api_password
  ota_password: !secret esphome_unused_esp13_ota_password

packages:
  device: !include devices/gosund_sp1.yaml
