---
# Unused; esp18
#
# Currently not in use, but here to be able to set it up
# again easily when needed.
#
# Its a Gosund SP1.
# https://frenck.link/gosund-sp1
#
substitutions:
  label: esp18
  slug: unused_esp18
  name: Unused esp18
  description: Unused Gosund SP1.
  api_password: !secret esphome_unused_esp18_api_password
  ota_password: !secret esphome_unused_esp18_ota_password

packages:
  device: !include devices/gosund_sp1.yaml
