---
alias: Landing Lights
description: >-
  Controls the landing lights.

  They mainly respond on motion; but also when the alarm arms.

id: 8a8bfc2d-a679-4605-a181-56a7dc7d1435
mode: queued

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - alarm_control_panel.house_alarm
      - binary_sensor.landing_motion
      - input_boolean.landing_automatic_lighting

condition:
  - condition: state
    entity_id: input_boolean.landing_automatic_lighting
    state: "on"

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: alarm_control_panel.house_alarm
            state:
              - disarmed
              - armed_home
          - condition: state
            entity_id: binary_sensor.landing_motion
            state: "on"
        sequence:
          - service: light.turn_on
            target:
              entity_id:
                - light.landing_ceiling
            data:
              transition: 1
    default:
      - service: light.turn_off
        target:
          area_id: landing
        data:
          transition: 5
